run:
  timeout: 5m
  buildvcs: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - gosec

issues:
  exclude-use-default: false